### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by atoy322** [atoy322/ls-exe#1]
- [x] remove hidden file name from output
- [ ] add some options like a GNU ls
- [ ] more color
- [ ] bad pprint behavior
